### ISSUE TITLE
Linear Progress Bar

### ISSUE THREAD

**Issue by thehendrix** [stasson/vue-mdc-adapter#491]
For some reason when I apply:
```css
.mdc-linear-progress__bar-inner {
  background-color: #4a90e2;
}
```
to change the progress bar color, it looks as though the rule gets overwritten by the --mdc-theme-primary color. If I change the style inside the Chrome inspect tool it works how it should. Is there a way to change the color with plain CSS or do I have to use that special SASS mixin to change the color?
